version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.local
    container_name: erdert_frontend
    stdin_open: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`erdert.dndnew.hu`)"
      - "traefik.http.routers.main.entrypoints=websecure"
      - "traefik.http.routers.main.tls.certresolver=myresolver"
    ports:
      - 5174:5174
    networks:
      - traefik-public
    command: npm run preview

networks:
  traefik-public:
    external: true
