version: "3.7"
services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    container_name: erdert_backend
    volumes:
      - ./:/var/www/html/erdert_backend
      - ./.env:/var/www/html/erdert_backend/.env
      - ./.env.production:/var/www/html/erdert_backend/.env.production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.app.localhost`)"
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env.production
    networks:
      - traefik-public
    depends_on:
      - mysql
      - traefik

  mysql:
    image: mysql
    container_name: sql_backend
    restart: unless-stopped
    env_file: ./backend/mysql.env
    ports:
      - 3307:3306
    volumes:
      - ./backend/docker/data/mysql:/var/lib/mysql
    networks:
      - traefik-public
    depends_on:
      - traefik

  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    container_name: erdert_frontend
    stdin_open: true
    volumes:
      - ./frontend:/var/www/html/erdert_frontend
      # - /var/www/html/erdert_frontend/node_modules
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`app.localhost`)"
    ports:
      - 5174:5174
    networks:
      - traefik-public
    depends_on:
      - api
      - traefik

  traefik:
    image: traefik:v2.9
    container_name: traefik
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
