version: "3.7"
services:
    api:
        build:
            context: ./
            dockerfile: Dockerfile.local
        container_name: erdert_backend
        volumes:
            - ./:/var/www/html/erdert_backend
            - ./.env.production:/var/www/html/erdert_backend/.env
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.api.rule=Host(`api.app.localhost`)"
        ports:
            - 8000:8000
        env_file:
            - .env.production
        networks:
            - traefik-public
        depends_on:
            - mysql
    mysql:
        image: mysql
        container_name: erdert_db
        restart: unless-stopped
        env_file: ./mysql.env
        ports:
            - 3307:3306
        volumes:
            - ./docker/data/mysql:/var/lib/mysql
        networks:
            - traefik-public

networks:
    traefik-public:
        external: true
