version: "3.7"
services:
    api:
        build:
            context: ./
            dockerfile: Dockerfile.local
        container_name: erdert_backend
        volumes:
            - ./:/var/www/html/erdert_backend
            - ./.env.production:/var/www/html/erdert_backend/.env
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.api.rule=Host(`backend.erdert.dndnew.hu`)"
            - "traefik.http.routers.api.entrypoints=websecure"
            - "traefik.http.routers.api.tls.certresolver=myresolver"
        ports:
            - 8000:8000
        env_file:
            - .env.production
        networks:
            - traefik-public

networks:
    traefik-public:
        external: true
