version: "3.7"
services:
  mysql:
    image: mysql
    container_name: erdert_db
    restart: unless-stopped
    env_file: ./mysql.env
    ports:
      - 3307:3306
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
